// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Constants.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Error source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Error.Recipes
{
    using System;

    /// <summary>
    /// Extension methods on type <see cref="Exception"/>.
    /// </summary>
#if !OBeautifulCodeErrorRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Error", "See package version number")]
    internal
#else
    public
#endif
        static class Constants
    {
        /// <summary>
        /// The key for the error code in <see cref="Exception.Data"/>.
        /// </summary>
        public const string ExceptionDataKeyForErrorCode = "__OBC_ErrorCode__";

        /// <summary>
        /// The key for the error codes vector in <see cref="Exception.Data"/>.
        /// </summary>
        public const string ExceptionDataKeyForErrorCodesVector = "__OBC_ErrorCodesVector__";
    }
}