// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ErrorCodeConstants.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Exception.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Exception.Recipes
{
    using System;

    /// <summary>
    /// Extension methods on type <see cref="Exception"/>.
    /// </summary>
#if !OBeautifulCodeExceptionRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Exception.Recipes", "See package version number")]
    internal
#else
    public
#endif
        static class ErrorCodeConstants
    {
        /// <summary>
        /// The key for the error code in <see cref="Exception.Data"/>.
        /// </summary>
        public const string ExceptionDataKeyForErrorCode = "__OBC_ErrorCode__";

        /// <summary>
        /// The key for the error codes vector in <see cref="Exception.Data"/>.
        /// </summary>
        public const string ExceptionDataKeyForErrorCodesVector = "__OBC_ErrorCodesVector__";
    }
}